export const StatusCodes = {
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    ERROR: 'ERROR',
    GAME_OVER: 'GAME_OVER',
    INAPPLICABLE_EVENT: 'INAPPLICABLE_EVENT',
    TODO_IMPLEMENT: 'TODO_IMPLEMENT',
};